services:
  # dbt container for running dbt commands
  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbt-container
    environment:
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_ROLE=${SNOWFLAKE_ROLE}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
      - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE}
      - SNOWFLAKE_SCHEMA=${SNOWFLAKE_SCHEMA}
    volumes:
      - ./dbt:/fantasy-football-challenge/dbt
      - ./dbt/profiles.yml:/root/.dbt/profiles.yml
    working_dir: /fantasy-football-challenge/dbt

  # Airflow container
  airflow-webserver:
    image: apache/airflow:2.4.0
    container_name: airflow-webserver
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW_SECRET_KEY}
      - AIRFLOW__WEBSERVER__WORKERS=4
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__USERNAME=${AIRFLOW_USERNAME}
      - AIRFLOW__WEBSERVER__PASSWORD=${AIRFLOW_PASSWORD}
    volumes:
      - ./airflow:/opt/airflow
      - ./dbt:/fantasy-football-challenge/dbt
      - ./init_airflow.sh:/opt/airflow/init_airflow.sh
    ports:
      - "8080:8080"
    depends_on:
      - dbt
    command: ["bash", "/opt/airflow/init_airflow.sh"]

  airflow-scheduler:
    image: apache/airflow:2.4.0
    container_name: airflow-scheduler
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./airflow:/opt/airflow
    depends_on:
      - dbt
    command: ["bash", "-c", "airflow scheduler"]

  airflow-worker:
    image: apache/airflow:2.4.0
    container_name: airflow-worker
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./airflow:/opt/airflow
    depends_on:
      - dbt
    command: ["bash", "-c", "airflow worker"]

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - airflow-db:/var/lib/postgresql/data

volumes:
  airflow-db: